### ISSUE TITLE
spring boot 配置 redis

### ISSUE THREAD

**Issue by techial1042** [techial1042/Blog#45]
### redis maven 依赖配置。

```xml
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-redis</artifactId>
            <version>RELEASE</version>
        </dependency>
```

### application.yml 配置

根据自己的需要进行配置即可，spring boot 里面都有默认配置。

不全部列举。

```yaml
spring:
  redis:
    database: 0     # 选择 redis 数据库
    host: localhost # ip
    port: 6379      # 端口
    timeout: 0      # 超时时间（毫秒）
    jedis:
      pool:
        min-idle: 0 # 最小空闲连接
        max-idle: 8 # 最大空闲连接
```

之后在 main 方法的那个类上，加入 `@EnableCaching` 注解。

**每个要想写入 redis 的类都需要 实现（implements） Serializable 这个接口。**，不然会报错。

### spring boot 缓存注解

- `@CacheConfig` 一般放在类上。
- `@Cacheable` 放在方法上，只缓存一次，之后只返回 缓存 里面的数据，不会刷新。
- `@CachePut` 放在方法上，都会调用函数。也是会刷新，将刷新的值放入 缓存。
- `@CacheEvict` 放在方法上，从缓存中移除数据。
